// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bank_account.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBankAccount = `-- name: CreateBankAccount :one
INSERT INTO bank_accounts ("user_id", "name", "bank_name", "account_type", "balance", "is_active")
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, user_id, name, bank_name, account_type, balance, is_active, created_at, updated_at
`

type CreateBankAccountParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	BankName    string         `json:"bank_name"`
	AccountType string         `json:"account_type"`
	Balance     pgtype.Numeric `json:"balance"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateBankAccount(ctx context.Context, arg CreateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, createBankAccount,
		arg.UserID,
		arg.Name,
		arg.BankName,
		arg.AccountType,
		arg.Balance,
		arg.IsActive,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BankName,
		&i.AccountType,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBankAccount = `-- name: DeleteBankAccount :exec
DELETE FROM bank_accounts WHERE "id" = $1
`

func (q *Queries) DeleteBankAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBankAccount, id)
	return err
}

const getBankAccountByID = `-- name: GetBankAccountByID :one
SELECT id, user_id, name, bank_name, account_type, balance, is_active, created_at, updated_at FROM bank_accounts WHERE "id" = $1
`

func (q *Queries) GetBankAccountByID(ctx context.Context, id uuid.UUID) (BankAccount, error) {
	row := q.db.QueryRow(ctx, getBankAccountByID, id)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BankName,
		&i.AccountType,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBankAccountByUserID = `-- name: GetBankAccountByUserID :many
SELECT id, user_id, name, bank_name, account_type, balance, is_active, created_at, updated_at FROM bank_accounts WHERE "user_id" = $1
`

func (q *Queries) GetBankAccountByUserID(ctx context.Context, userID uuid.UUID) ([]BankAccount, error) {
	rows, err := q.db.Query(ctx, getBankAccountByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankAccount
	for rows.Next() {
		var i BankAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.BankName,
			&i.AccountType,
			&i.Balance,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankAccount = `-- name: UpdateBankAccount :one
UPDATE bank_accounts SET "name" = $2, "bank_name" = $3, "account_type" = $4, "balance" = $5, "is_active" = $6
WHERE "id" = $1
RETURNING id, user_id, name, bank_name, account_type, balance, is_active, created_at, updated_at
`

type UpdateBankAccountParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	BankName    string         `json:"bank_name"`
	AccountType string         `json:"account_type"`
	Balance     pgtype.Numeric `json:"balance"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateBankAccount(ctx context.Context, arg UpdateBankAccountParams) (BankAccount, error) {
	row := q.db.QueryRow(ctx, updateBankAccount,
		arg.ID,
		arg.Name,
		arg.BankName,
		arg.AccountType,
		arg.Balance,
		arg.IsActive,
	)
	var i BankAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.BankName,
		&i.AccountType,
		&i.Balance,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
