// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories ("user_id", "name", "category_type", "color", "icon")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, category_type, color, icon
`

type CreateCategoryParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	Name         string      `json:"name"`
	CategoryType string      `json:"category_type"`
	Color        pgtype.Text `json:"color"`
	Icon         pgtype.Text `json:"icon"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.CategoryType,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CategoryType,
		&i.Color,
		&i.Icon,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE "id" = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, category_type, color, icon FROM categories WHERE "id" = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CategoryType,
		&i.Color,
		&i.Icon,
	)
	return i, err
}

const getCategoryByUserID = `-- name: GetCategoryByUserID :many
SELECT id, user_id, name, category_type, color, icon FROM categories WHERE "user_id" = $1
`

func (q *Queries) GetCategoryByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoryByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CategoryType,
			&i.Color,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET "name" = $2, "category_type" = $3, "color" = $4, "icon" = $5
WHERE "id" = $1
RETURNING id, user_id, name, category_type, color, icon
`

type UpdateCategoryParams struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	CategoryType string      `json:"category_type"`
	Color        pgtype.Text `json:"color"`
	Icon         pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.CategoryType,
		arg.Color,
		arg.Icon,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CategoryType,
		&i.Color,
		&i.Icon,
	)
	return i, err
}
