// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_card.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCreditCard = `-- name: CreateCreditCard :one
INSERT INTO credit_cards ("user_id", "name", "credit_limit", "close_day", "due_day", "is_active")
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, user_id, name, credit_limit, close_day, due_day, is_active, created_at, updated_at
`

type CreateCreditCardParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	CreditLimit pgtype.Numeric `json:"credit_limit"`
	CloseDay    int32          `json:"close_day"`
	DueDay      int32          `json:"due_day"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, createCreditCard,
		arg.UserID,
		arg.Name,
		arg.CreditLimit,
		arg.CloseDay,
		arg.DueDay,
		arg.IsActive,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreditLimit,
		&i.CloseDay,
		&i.DueDay,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCreditCard = `-- name: DeleteCreditCard :exec
DELETE FROM credit_cards WHERE "id" = $1
`

func (q *Queries) DeleteCreditCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCreditCard, id)
	return err
}

const getCreditCardByID = `-- name: GetCreditCardByID :one
SELECT id, user_id, name, credit_limit, close_day, due_day, is_active, created_at, updated_at FROM credit_cards WHERE "id" = $1
`

func (q *Queries) GetCreditCardByID(ctx context.Context, id uuid.UUID) (CreditCard, error) {
	row := q.db.QueryRow(ctx, getCreditCardByID, id)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreditLimit,
		&i.CloseDay,
		&i.DueDay,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditCardByUserID = `-- name: GetCreditCardByUserID :many
SELECT id, user_id, name, credit_limit, close_day, due_day, is_active, created_at, updated_at FROM credit_cards WHERE "user_id" = $1
`

func (q *Queries) GetCreditCardByUserID(ctx context.Context, userID uuid.UUID) ([]CreditCard, error) {
	rows, err := q.db.Query(ctx, getCreditCardByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditCard
	for rows.Next() {
		var i CreditCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreditLimit,
			&i.CloseDay,
			&i.DueDay,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditCard = `-- name: UpdateCreditCard :one
UPDATE credit_cards SET "name" = $2, "credit_limit" = $3, "close_day" = $4, "due_day" = $5, "is_active" = $6
WHERE "id" = $1
RETURNING id, user_id, name, credit_limit, close_day, due_day, is_active, created_at, updated_at
`

type UpdateCreditCardParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	CreditLimit pgtype.Numeric `json:"credit_limit"`
	CloseDay    int32          `json:"close_day"`
	DueDay      int32          `json:"due_day"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateCreditCard(ctx context.Context, arg UpdateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRow(ctx, updateCreditCard,
		arg.ID,
		arg.Name,
		arg.CreditLimit,
		arg.CloseDay,
		arg.DueDay,
		arg.IsActive,
	)
	var i CreditCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreditLimit,
		&i.CloseDay,
		&i.DueDay,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
