// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices ("card_id", "reference_date", "due_date", "total_amount", "status", "paid_at")
VALUES ($1,$2,$3,$4,$5,$6)
RETURNING id, card_id, reference_date, due_date, total_amount, status, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	CardID        uuid.UUID          `json:"card_id"`
	ReferenceDate pgtype.Date        `json:"reference_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Status        string             `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.CardID,
		arg.ReferenceDate,
		arg.DueDate,
		arg.TotalAmount,
		arg.Status,
		arg.PaidAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ReferenceDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE "id" = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoiceByCardID = `-- name: GetInvoiceByCardID :many
SELECT id, card_id, reference_date, due_date, total_amount, status, paid_at, created_at, updated_at FROM invoices WHERE "card_id" = $1
`

func (q *Queries) GetInvoiceByCardID(ctx context.Context, cardID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, getInvoiceByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.ReferenceDate,
			&i.DueDate,
			&i.TotalAmount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, card_id, reference_date, due_date, total_amount, status, paid_at, created_at, updated_at FROM invoices WHERE "id" = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ReferenceDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET "total_amount" = $2, "status" = $3, "paid_at" = $4
WHERE "id" = $1
RETURNING id, card_id, reference_date, due_date, total_amount, status, paid_at, created_at, updated_at
`

type UpdateInvoiceParams struct {
	ID          uuid.UUID          `json:"id"`
	TotalAmount pgtype.Numeric     `json:"total_amount"`
	Status      string             `json:"status"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.TotalAmount,
		arg.Status,
		arg.PaidAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.ReferenceDate,
		&i.DueDate,
		&i.TotalAmount,
		&i.Status,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
