// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BankAccount struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	BankName    string             `json:"bank_name"`
	AccountType string             `json:"account_type"`
	Balance     pgtype.Numeric     `json:"balance"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID           uuid.UUID   `json:"id"`
	UserID       uuid.UUID   `json:"user_id"`
	Name         string      `json:"name"`
	CategoryType string      `json:"category_type"`
	Color        pgtype.Text `json:"color"`
	Icon         pgtype.Text `json:"icon"`
}

type CreditCard struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Name        string             `json:"name"`
	CreditLimit pgtype.Numeric     `json:"credit_limit"`
	CloseDay    int32              `json:"close_day"`
	DueDay      int32              `json:"due_day"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CreditCardTransaction struct {
	ID                 uuid.UUID          `json:"id"`
	CardID             uuid.UUID          `json:"card_id"`
	CategoryID         uuid.UUID          `json:"category_id"`
	InvoiceID          pgtype.UUID        `json:"invoice_id"`
	Amount             pgtype.Numeric     `json:"amount"`
	Description        string             `json:"description"`
	Installments       int32              `json:"installments"`
	CurrentInstallment int32              `json:"current_installment"`
	InstallmentValue   pgtype.Numeric     `json:"installment_value"`
	TransactionDate    pgtype.Date        `json:"transaction_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Invoice struct {
	ID            uuid.UUID          `json:"id"`
	CardID        uuid.UUID          `json:"card_id"`
	ReferenceDate pgtype.Date        `json:"reference_date"`
	DueDate       pgtype.Date        `json:"due_date"`
	TotalAmount   pgtype.Numeric     `json:"total_amount"`
	Status        string             `json:"status"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PlannedExpense struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Description string             `json:"description"`
	Amount      pgtype.Numeric     `json:"amount"`
	DueDay      int32              `json:"due_day"`
	Frequency   string             `json:"frequency"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PlannedIncome struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Description string             `json:"description"`
	Amount      pgtype.Numeric     `json:"amount"`
	DueDay      int32              `json:"due_day"`
	Frequency   string             `json:"frequency"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID               uuid.UUID          `json:"id"`
	AccountID        uuid.UUID          `json:"account_id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	InvoiceID        pgtype.UUID        `json:"invoice_id"`
	PlannedIncomeID  pgtype.UUID        `json:"planned_income_id"`
	PlannedExpenseID pgtype.UUID        `json:"planned_expense_id"`
	Amount           pgtype.Numeric     `json:"amount"`
	TransactionType  string             `json:"transaction_type"`
	Description      string             `json:"description"`
	TransactionDate  pgtype.Date        `json:"transaction_date"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
