// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: planned_expense.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlannedExpense = `-- name: CreatePlannedExpense :one
INSERT INTO planned_expenses ("user_id", "account_id", "category_id", "amount", "due_day", "start_date", "end_date", "description", "frequency", "is_active")
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at
`

type CreatePlannedExpenseParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	AccountID   uuid.UUID      `json:"account_id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	DueDay      int32          `json:"due_day"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	Description string         `json:"description"`
	Frequency   string         `json:"frequency"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreatePlannedExpense(ctx context.Context, arg CreatePlannedExpenseParams) (PlannedExpense, error) {
	row := q.db.QueryRow(ctx, createPlannedExpense,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.DueDay,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Frequency,
		arg.IsActive,
	)
	var i PlannedExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlannedExpense = `-- name: DeletePlannedExpense :exec
DELETE FROM planned_expenses WHERE "id" = $1
`

func (q *Queries) DeletePlannedExpense(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlannedExpense, id)
	return err
}

const getPlannedExpenseByID = `-- name: GetPlannedExpenseByID :one
SELECT id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at FROM planned_expenses WHERE "id" = $1
`

func (q *Queries) GetPlannedExpenseByID(ctx context.Context, id uuid.UUID) (PlannedExpense, error) {
	row := q.db.QueryRow(ctx, getPlannedExpenseByID, id)
	var i PlannedExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlannedExpenseByUserID = `-- name: GetPlannedExpenseByUserID :many
SELECT id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at FROM planned_expenses WHERE "user_id" = $1
`

func (q *Queries) GetPlannedExpenseByUserID(ctx context.Context, userID uuid.UUID) ([]PlannedExpense, error) {
	rows, err := q.db.Query(ctx, getPlannedExpenseByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedExpense
	for rows.Next() {
		var i PlannedExpense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.DueDay,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlannedExpense = `-- name: UpdatePlannedExpense :one
UPDATE planned_expenses SET "amount" = $2, "due_day" = $3, "start_date" = $4, "end_date" = $5, "description" = $6, "frequency" = $7, "is_active" = $8
WHERE "id" = $1
RETURNING id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at
`

type UpdatePlannedExpenseParams struct {
	ID          uuid.UUID      `json:"id"`
	Amount      pgtype.Numeric `json:"amount"`
	DueDay      int32          `json:"due_day"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	Description string         `json:"description"`
	Frequency   string         `json:"frequency"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdatePlannedExpense(ctx context.Context, arg UpdatePlannedExpenseParams) (PlannedExpense, error) {
	row := q.db.QueryRow(ctx, updatePlannedExpense,
		arg.ID,
		arg.Amount,
		arg.DueDay,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Frequency,
		arg.IsActive,
	)
	var i PlannedExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
