// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: planned_income.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlannedIncome = `-- name: CreatePlannedIncome :one
INSERT INTO planned_incomes ("user_id", "account_id", "category_id", "amount", "due_day", "start_date", "end_date", "description", "frequency", "is_active")
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
RETURNING id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at
`

type CreatePlannedIncomeParams struct {
	UserID      uuid.UUID      `json:"user_id"`
	AccountID   uuid.UUID      `json:"account_id"`
	CategoryID  uuid.UUID      `json:"category_id"`
	Amount      pgtype.Numeric `json:"amount"`
	DueDay      int32          `json:"due_day"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	Description string         `json:"description"`
	Frequency   string         `json:"frequency"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreatePlannedIncome(ctx context.Context, arg CreatePlannedIncomeParams) (PlannedIncome, error) {
	row := q.db.QueryRow(ctx, createPlannedIncome,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Amount,
		arg.DueDay,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Frequency,
		arg.IsActive,
	)
	var i PlannedIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlannedIncome = `-- name: DeletePlannedIncome :exec
DELETE FROM planned_incomes WHERE "id" = $1
`

func (q *Queries) DeletePlannedIncome(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlannedIncome, id)
	return err
}

const getPlannedIncomeByID = `-- name: GetPlannedIncomeByID :one
SELECT id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at FROM planned_incomes WHERE "id" = $1
`

func (q *Queries) GetPlannedIncomeByID(ctx context.Context, id uuid.UUID) (PlannedIncome, error) {
	row := q.db.QueryRow(ctx, getPlannedIncomeByID, id)
	var i PlannedIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlannedIncomeByUserID = `-- name: GetPlannedIncomeByUserID :many
SELECT id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at FROM planned_incomes WHERE "user_id" = $1
`

func (q *Queries) GetPlannedIncomeByUserID(ctx context.Context, userID uuid.UUID) ([]PlannedIncome, error) {
	rows, err := q.db.Query(ctx, getPlannedIncomeByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannedIncome
	for rows.Next() {
		var i PlannedIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Description,
			&i.Amount,
			&i.DueDay,
			&i.Frequency,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlannedIncome = `-- name: UpdatePlannedIncome :one
UPDATE planned_incomes SET "amount" = $2, "due_day" = $3, "start_date" = $4, "end_date" = $5, "description" = $6, "frequency" = $7, "is_active" = $8
WHERE "id" = $1
RETURNING id, user_id, account_id, category_id, description, amount, due_day, frequency, start_date, end_date, is_active, created_at, updated_at
`

type UpdatePlannedIncomeParams struct {
	ID          uuid.UUID      `json:"id"`
	Amount      pgtype.Numeric `json:"amount"`
	DueDay      int32          `json:"due_day"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	Description string         `json:"description"`
	Frequency   string         `json:"frequency"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdatePlannedIncome(ctx context.Context, arg UpdatePlannedIncomeParams) (PlannedIncome, error) {
	row := q.db.QueryRow(ctx, updatePlannedIncome,
		arg.ID,
		arg.Amount,
		arg.DueDay,
		arg.StartDate,
		arg.EndDate,
		arg.Description,
		arg.Frequency,
		arg.IsActive,
	)
	var i PlannedIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Description,
		&i.Amount,
		&i.DueDay,
		&i.Frequency,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
