// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions ("account_id", "category_id", "invoice_id", "planned_income_id", "planned_expense_id", "amount", "transaction_type", "description", "transaction_date")
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at
`

type CreateTransactionParams struct {
	AccountID        uuid.UUID      `json:"account_id"`
	CategoryID       uuid.UUID      `json:"category_id"`
	InvoiceID        pgtype.UUID    `json:"invoice_id"`
	PlannedIncomeID  pgtype.UUID    `json:"planned_income_id"`
	PlannedExpenseID pgtype.UUID    `json:"planned_expense_id"`
	Amount           pgtype.Numeric `json:"amount"`
	TransactionType  string         `json:"transaction_type"`
	Description      string         `json:"description"`
	TransactionDate  pgtype.Date    `json:"transaction_date"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.CategoryID,
		arg.InvoiceID,
		arg.PlannedIncomeID,
		arg.PlannedExpenseID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.InvoiceID,
		&i.PlannedIncomeID,
		&i.PlannedExpenseID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE "id" = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getTransactionByAccountID = `-- name: GetTransactionByAccountID :many
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "account_id" = $1
`

func (q *Queries) GetTransactionByAccountID(ctx context.Context, accountID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByAccountID, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.InvoiceID,
			&i.PlannedIncomeID,
			&i.PlannedExpenseID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByCategoryID = `-- name: GetTransactionByCategoryID :many
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "category_id" = $1
`

func (q *Queries) GetTransactionByCategoryID(ctx context.Context, categoryID uuid.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByCategoryID, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.InvoiceID,
			&i.PlannedIncomeID,
			&i.PlannedExpenseID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "id" = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.InvoiceID,
		&i.PlannedIncomeID,
		&i.PlannedExpenseID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionByInvoiceID = `-- name: GetTransactionByInvoiceID :many
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "invoice_id" = $1
`

func (q *Queries) GetTransactionByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.InvoiceID,
			&i.PlannedIncomeID,
			&i.PlannedExpenseID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByPlannedExpenseID = `-- name: GetTransactionByPlannedExpenseID :many
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "planned_expense_id" = $1
`

func (q *Queries) GetTransactionByPlannedExpenseID(ctx context.Context, plannedExpenseID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByPlannedExpenseID, plannedExpenseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.InvoiceID,
			&i.PlannedIncomeID,
			&i.PlannedExpenseID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByPlannedIncomeID = `-- name: GetTransactionByPlannedIncomeID :many
SELECT id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at FROM transactions WHERE "planned_income_id" = $1
`

func (q *Queries) GetTransactionByPlannedIncomeID(ctx context.Context, plannedIncomeID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionByPlannedIncomeID, plannedIncomeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.InvoiceID,
			&i.PlannedIncomeID,
			&i.PlannedExpenseID,
			&i.Amount,
			&i.TransactionType,
			&i.Description,
			&i.TransactionDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions SET "amount" = $2, "transaction_type" = $3, "description" = $4, "transaction_date" = $5
WHERE "id" = $1
RETURNING id, account_id, category_id, invoice_id, planned_income_id, planned_expense_id, amount, transaction_type, description, transaction_date, created_at
`

type UpdateTransactionParams struct {
	ID              uuid.UUID      `json:"id"`
	Amount          pgtype.Numeric `json:"amount"`
	TransactionType string         `json:"transaction_type"`
	Description     string         `json:"description"`
	TransactionDate pgtype.Date    `json:"transaction_date"`
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.Amount,
		arg.TransactionType,
		arg.Description,
		arg.TransactionDate,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.InvoiceID,
		&i.PlannedIncomeID,
		&i.PlannedExpenseID,
		&i.Amount,
		&i.TransactionType,
		&i.Description,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}
